window.upsellConfig=window.upsellConfig||{};
Object.assign(window.upsellConfig,
{
	"plusServiceAddonMapping":{
		"PREMIUMCAREPLUS_NB": "ADP,SB,SMARTPERFORMANCE,DM",
		"PREMIUMCAREPLUS_NOSB_NB": "ADP,SMARTPERFORMANCE,DM",
		"PREMIUMCAREDEPOTPLUS_NB": "ADP,SB,SMARTPERFORMANCE,DM",
		"PREMIUMCAREDEPOTPLUS_NOSB_NB": "ADP,SMARTPERFORMANCE,DM",
		"PREMIUMCAREPLUS_DT": "SMARTPERFORMANCE,DM",
		"PREMIUMCAREDEPOTPLUS_DT": "SMARTPERFORMANCE,DM",
		"PREMIUMCAREDEPOTPLUS_CHROMEBOOK": "ADP,SB,DM",
		"PREMIUMCAREDEPOTPLUS_NOSB_CHROMEBOOK": "ADP,DM",
		"PREMIUMCAREDEPOTPLUS_ANDROID": "ADPONE,DM"
	}
}
);